/* Phase 1 encounter catalogue: region-aware records with visual art and itemised drops. */
(function () {
  const item = (itemId, name, tier, chance) => ({ itemId, name, tier, chance });
  const encounter = (id, name, type, region, risk, icon, color, stats, detail, drops) => ({ id, name, type, region, risk, icon, color, stats, ...detail, drops });

  window.AlbionBestiaryData = [
    encounter('mists-griffin', 'bestiary-griffin', 'mob', 'bestiary-regionMists', 'high', '🦅', '#a78bfa',
      { hp: '18,400', damage: '420–580', fame: '8,200', silver: '18K–42K', respawn: '10–18 dk' },
      { summary: 'bestiary-griffinSummary', traits: ['bestiary-griffinTrait1', 'bestiary-griffinTrait2'], weaknesses: ['bestiary-griffinWeak1', 'bestiary-griffinWeak2'], roles: 'bestiary-roleSoloDuo', strategy: 'bestiary-griffinStrategy', areas: ['bestiary-areaMists'] },
      [item('T6_MAIN_FROSTSTAFF', 'bestiary-dropMistChest', 'T6', 'common'), item('T6_OFF_TOTEM_KEEPER', 'bestiary-dropGriffinFeather', 'T6', 'uncommon'), item('T6_RUNE', 'bestiary-dropRune', 'T6', 'rare')]),
    encounter('mists-mist-stalker', 'bestiary-mistStalker', 'mob', 'bestiary-regionMists', 'medium', '🐺', '#c084fc',
      { hp: '9,800', damage: '230–330', fame: '3,600', silver: '6K–16K', respawn: '6–12 dk' },
      { summary: 'bestiary-mistStalkerSummary', traits: ['bestiary-stalkerTrait1', 'bestiary-stalkerTrait2'], weaknesses: ['bestiary-stalkerWeak1'], roles: 'bestiary-roleSolo', strategy: 'bestiary-stalkerStrategy', areas: ['bestiary-areaMists'] },
      [item('T5_MAIN_CURSEDSTAFF', 'bestiary-dropMistChest', 'T5', 'common'), item('T5_RUNE', 'bestiary-dropRune', 'T5', 'uncommon')]),
    encounter('royal-heretic-miner', 'bestiary-hereticMiner', 'mob', 'bestiary-regionRoyal', 'low', '⛏️', '#f59e0b',
      { hp: '2,900', damage: '75–110', fame: '900', silver: '1K–4K', respawn: '2–5 dk' },
      { summary: 'bestiary-hereticSummary', traits: ['bestiary-hereticTrait1'], weaknesses: ['bestiary-hereticWeak1'], roles: 'bestiary-roleGatherer', strategy: 'bestiary-hereticStrategy', areas: ['bestiary-areaRoyal'] },
      [item('T4_ORE', 'bestiary-dropOre', 'T4', 'common'), item('T4_SKILLBOOK', 'bestiary-dropFameBook', 'T4', 'rare')]),
    encounter('royal-undead-reaper', 'bestiary-undeadReaper', 'mob', 'bestiary-regionRoyal', 'medium', '💀', '#64748b',
      { hp: '6,200', damage: '160–240', fame: '2,100', silver: '3K–9K', respawn: '4–8 dk' },
      { summary: 'bestiary-undeadSummary', traits: ['bestiary-undeadTrait1', 'bestiary-undeadTrait2'], weaknesses: ['bestiary-undeadWeak1'], roles: 'bestiary-roleSoloDuo', strategy: 'bestiary-undeadStrategy', areas: ['bestiary-areaRoyal', 'bestiary-areaStatic'] },
      [item('T5_SOUL', 'bestiary-dropSoul', 'T5', 'uncommon'), item('T5_RUNE', 'bestiary-dropRune', 'T5', 'common')]),
    encounter('roads-avalonian-construct', 'bestiary-construct', 'mob', 'bestiary-regionRoads', 'high', '🤖', '#38bdf8',
      { hp: '24,000', damage: '480–720', fame: '12,500', silver: '25K–70K', respawn: '12–25 dk' },
      { summary: 'bestiary-constructSummary', traits: ['bestiary-constructTrait1', 'bestiary-constructTrait2'], weaknesses: ['bestiary-constructWeak1', 'bestiary-constructWeak2'], roles: 'bestiary-roleGroup', strategy: 'bestiary-constructStrategy', areas: ['bestiary-areaRoads', 'bestiary-areaAvalon'] },
      [item('T7_SHARD_AVALONIAN', 'bestiary-dropShard', 'T7', 'uncommon'), item('T7_BAG', 'bestiary-dropAvalonianBag', 'T7', 'rare'), item('T6_2H_CROSSBOW', 'bestiary-dropAvalonArtefact', 'T6', 'rare')]),
    encounter('roads-avalonian-earthmother', 'bestiary-earthmother', 'boss', 'bestiary-regionRoads', 'high', '🌿', '#22c55e',
      { hp: '78,000', damage: '950–1,420', fame: '48,000', silver: '120K–360K', respawn: '30–60 dk' },
      { summary: 'bestiary-earthmotherSummary', traits: ['bestiary-earthmotherTrait1', 'bestiary-earthmotherTrait2'], weaknesses: ['bestiary-earthmotherWeak1'], roles: 'bestiary-roleGroup', strategy: 'bestiary-earthmotherStrategy', areas: ['bestiary-areaRoads', 'bestiary-areaAvalon'] },
      [item('T8_SHARD_AVALONIAN', 'bestiary-dropShard', 'T8', 'uncommon'), item('T8_BAG', 'bestiary-dropAvalonianBag', 'T8', 'rare'), item('T8_ARTEFACT_ARMOR_PLATE_HELL', 'bestiary-dropAvalonArtefact', 'T8', 'veryRare')]),
    encounter('static-keeper-elder', 'bestiary-keeperElder', 'boss', 'bestiary-regionStatic', 'high', '🪓', '#f59e0b',
      { hp: '64,000', damage: '720–1,100', fame: '31,000', silver: '70K–220K', respawn: '20–40 dk' },
      { summary: 'bestiary-keeperSummary', traits: ['bestiary-keeperTrait1', 'bestiary-keeperTrait2'], weaknesses: ['bestiary-keeperWeak1'], roles: 'bestiary-roleGroup', strategy: 'bestiary-keeperStrategy', areas: ['bestiary-areaStatic', 'bestiary-areaRoyal'] },
      [item('T8_ARTEFACT_ARMOR_CLOTH_KEEPER', 'bestiary-dropKeeperArtefact', 'T8', 'rare'), item('T7_RUNE', 'bestiary-dropRune', 'T7', 'common'), item('T8_BAG', 'bestiary-dropBag', 'T8', 'uncommon')]),
    encounter('morgana-demon', 'bestiary-morganaDemon', 'mob', 'bestiary-regionRoyal', 'medium', '🔥', '#a855f7',
      { hp: '11,600', damage: '280–410', fame: '4,400', silver: '8K–22K', respawn: '6–14 dk' },
      { summary: 'bestiary-morganaSummary', traits: ['bestiary-morganaTrait1', 'bestiary-morganaTrait2'], weaknesses: ['bestiary-morganaWeak1'], roles: 'bestiary-roleSolo', strategy: 'bestiary-morganaStrategy', areas: ['bestiary-areaRoyal', 'bestiary-areaMists'] },
      [item('T6_ARTEFACT_ARMOR_PLATE_MORGANA', 'bestiary-dropMorganaToken', 'T6', 'uncommon'), item('T6_ARTEFACT_ARMOR_CLOTH_MORGANA', 'bestiary-dropMorganaArtefact', 'T6', 'rare')]),
    encounter('corrupted-hunter', 'bestiary-corruptedHunter', 'event', 'bestiary-regionCorrupted', 'medium', '👁️', '#fb7185',
      { hp: '28,000', damage: '380–620', fame: '18,000', silver: '40K–160K', respawn: 'run-based' },
      { summary: 'bestiary-corruptedSummary', traits: ['bestiary-corruptedTrait1', 'bestiary-corruptedTrait2'], weaknesses: ['bestiary-corruptedWeak1'], roles: 'bestiary-roleSolo', strategy: 'bestiary-corruptedStrategy', areas: ['bestiary-areaCorrupted'] },
      [item('T6_RUNE', 'bestiary-dropRune', 'T6', 'common'), item('T6_ARTEFACT_ARMOR_LEATHER_UNDEAD', 'bestiary-dropCorruptedChest', 'T6', 'uncommon')]),
    encounter('hellgate-demon', 'bestiary-hellgateDemon', 'boss', 'bestiary-regionHellgate', 'high', '😈', '#ef4444',
      { hp: '54,000', damage: '640–980', fame: '27,000', silver: '60K–190K', respawn: 'instance' },
      { summary: 'bestiary-hellgateSummary', traits: ['bestiary-hellgateTrait1', 'bestiary-hellgateTrait2'], weaknesses: ['bestiary-hellgateWeak1'], roles: 'bestiary-roleGroup', strategy: 'bestiary-hellgateStrategy', areas: ['bestiary-areaHellgate'] },
      [item('T7_SOUL', 'bestiary-dropSoul', 'T7', 'uncommon'), item('T7_2H_AXE', 'bestiary-dropDemonicChest', 'T7', 'rare')]),
    encounter('world-boss-behemoth', 'bestiary-behemoth', 'event', 'bestiary-regionOpenWorld', 'high', '🐲', '#ef4444',
      { hp: '180,000', damage: '1,100–1,850', fame: '110,000', silver: '300K–1.2M', respawn: 'event-window' },
      { summary: 'bestiary-behemothSummary', traits: ['bestiary-behemothTrait1', 'bestiary-behemothTrait2'], weaknesses: ['bestiary-behemothWeak1', 'bestiary-behemothWeak2'], roles: 'bestiary-roleLargeGroup', strategy: 'bestiary-behemothStrategy', areas: ['bestiary-areaOpenWorld', 'bestiary-areaBlack'] },
      [item('T8_BAG', 'bestiary-dropBag', 'T8', 'uncommon'), item('T8_SKILLBOOK', 'bestiary-dropFameBook', 'T8', 'rare'), item('T8_ARTEFACT_MAIN_SPEAR_KEEPER', 'bestiary-dropWorldArtefact', 'T8', 'veryRare')]),
    encounter('faction-general', 'bestiary-factionGeneral', 'event', 'bestiary-regionFaction', 'medium', '🚩', '#22c55e',
      { hp: '92,000', damage: '760–1,200', fame: '55,000', silver: '100K–420K', respawn: 'event-window' },
      { summary: 'bestiary-factionSummary', traits: ['bestiary-factionTrait1'], weaknesses: ['bestiary-factionWeak1'], roles: 'bestiary-roleLargeGroup', strategy: 'bestiary-factionStrategy', areas: ['bestiary-areaFaction'] },
      [item('T6_SKILLBOOK', 'bestiary-dropFameBook', 'T6', 'common'), item('T6_OFF_SHIELD', 'bestiary-dropFactionChest', 'T6', 'uncommon')]),
    encounter('world-tree-event', 'bestiary-worldTree', 'event', 'bestiary-regionOpenWorld', 'low', '🌳', '#84cc16',
      { hp: '—', damage: '—', fame: '—', silver: '80K–300K/saat', respawn: 'gathering-window' },
      { summary: 'bestiary-treeSummary', traits: ['bestiary-treeTrait1'], weaknesses: ['bestiary-treeWeak1'], roles: 'bestiary-roleGatherer', strategy: 'bestiary-treeStrategy', areas: ['bestiary-areaOpenWorld', 'bestiary-areaBlack'] },
      [item('T6_FIBER', 'bestiary-dropFiber', 'T6', 'common'), item('T7_FIBER', 'bestiary-dropFiber', 'T7', 'uncommon'), item('T8_FIBER', 'bestiary-dropFiber', 'T8', 'rare')])
  ];
})();
