/* Structured operations catalogue. Values are guide estimates and intentionally easy to extend. */
(function () {
  const drop = (name, itemId, tier, chance, note) => ({ name, itemId, tier, chance, note });
  const mob = (id, name, family, type, region, risk, icon, color, hp, damage, fame, respawn, summary, traits, mechanics, roles, drops, phaseKey = '') => ({ id, name, family, type, region, risk, icon, color, stats: { hp, damage, fame, respawn }, summary, traits, mechanics, roles, drops, phaseKey });
  const encounters = [
    mob('mists-griffin-ops', 'Mists Griffin', 'Griffin', 'mob', 'Mists', 'high', '🦅', '#a78bfa', '18.4K', '420–580', '8.2K', '10–18 dk', 'Mists içindeki elit uçan avcı; dalış ve takip baskısıyla küçük ekipleri rotasından çıkarır.', ['Dalış telegraphı', 'Hareketli hedef takibi'], ['Dalıştan sonra 4 saniyelik burst penceresi', 'Görüş hattı kesilirse takip sıfırlanır'], 'Solo / Duo mobil set', [drop('Griffin Tüyü', 'T6_OFF_TOTEM_KEEPER', 'T6', 'Olası', 'Mists özel düşümü'), drop('Mists Sandığı', 'T6_MAIN_FROSTSTAFF', 'T6', 'Sık', 'Karşılaşma sandığı'), drop('Rune', 'T6_RUNE', 'T6', 'Nadir', 'Genel boss ödülü')], 'griffin'),
    mob('mists-wisp', 'Mist Wisp', 'Wisp', 'mob', 'Mists', 'medium', '✨', '#c084fc', '7.2K', '180–260', '2.8K', '5–10 dk', 'Mists geçitleri çevresinde görünen, kısa menzilli patlama yapan gezgin yaratık.', ['Kısa teleport', 'Patlama çekirdeği'], ['Teleport sonrası yere bıraktığı alanı terk et', 'Düşük canında kaçış hızlanır'], 'Solo farm / Gatherer', [drop('Mist Chest', 'T5_MAIN_CURSEDSTAFF', 'T5', 'Olası', 'Mists chest'), drop('Royal Sigil', 'QUESTITEM_TOKEN_ROYAL', 'T5', 'Nadir', 'Nadir varyant')]),
    mob('royal-heretic-family', 'Heretic Madencisi', 'Heretic', 'mob', 'Royal Kıtası', 'low', '⛏️', '#f59e0b', '2.9K', '75–110', '900', '2–5 dk', 'Royal bölgelerinde kaynakçı rotaları çevresinde bulunan düşük riskli insan mob ailesi.', ['Madenci alarmı', 'Yakın dövüş'], ['Alarm çubuğunu kes', 'Kaynak taşırken çevreyi kontrol et'], 'Solo / Gatherer', [drop('Cevher', 'T4_ORE', 'T4', 'Sık', 'Bölgesel kaynak'), drop('Fame Book', 'T4_SKILLBOOK', 'T4', 'Nadir', 'Genel ödül')]),
    mob('royal-undead-family', 'Undead Reaper', 'Undead', 'mob', 'Royal Kıtası', 'medium', '💀', '#64748b', '6.2K', '160–240', '2.1K', '4–8 dk', 'Undead aile setinin hızlı yakın dövüş varyantı; statik dungeon girişlerini korur.', ['Korku bakışı', 'Can çalma'], ['Korku bakışında yön değiştir', 'Can çalma kanalını kes'], 'Solo / Duo', [drop('Soul', 'T5_SOUL', 'T5', 'Olası', 'Undead bölgesi'), drop('Rune', 'T5_RUNE', 'T5', 'Sık', 'Genel ödül')]),
    mob('keeper-family', 'Keeper Warrior', 'Keeper', 'mob', 'Static Dungeon', 'medium', '🪓', '#f59e0b', '8.8K', '220–360', '3.9K', '6–12 dk', 'Keeper dungeon koridorlarında tank baskısı kuran ağır zırhlı aile.', ['Ön koni', 'Zırh kırma'], ['Ön koniden uzak dur', 'Zırh kırmayı purge veya cleanse ile yönet'], 'Duo / Group', [drop('Keeper Rune', 'T6_RUNE', 'T6', 'Olası', 'Keeper loot'), drop('Bag', 'T6_BAG', 'T6', 'Nadir', 'Dungeon loot')]),
    mob('morgana-family', 'Morgana Warlock', 'Morgana', 'mob', 'Royal / Static', 'medium', '🔥', '#a855f7', '11.6K', '280–410', '4.4K', '6–14 dk', 'Morgana ailesinin menzilli büyücü varyantı; alan kontrolüyle kaçış yollarını daraltır.', ['Ateş alanı', 'Menzilli curse'], ['Ateş alanını dışarı taşı', 'Curse yığınını zamanında temizle'], 'Solo / Duo', [drop('Morgana Token', 'T6_ARTEFACT_ARMOR_PLATE_MORGANA', 'T6', 'Olası', 'Morgana içeriği'), drop('Cloth Artefact', 'T6_ARTEFACT_ARMOR_CLOTH_MORGANA', 'T6', 'Nadir', 'Artefact')]),
    mob('avalonian-soldier-family', 'Avalonian Soldier', 'Avalonian', 'mob', 'Roads of Avalon', 'high', '🤖', '#38bdf8', '24K', '480–720', '12.5K', '12–25 dk', 'Avalonian yollarında grup koordinasyonu gerektiren ağır piyade ailesi.', ['Kalkan duvarı', 'Shockwave'], ['Kalkan duvarını arkadan kır', 'Shockwave öncesi dağılımı aç'], 'Group', [drop('Avalonian Shard', 'T7_SHARD_AVALONIAN', 'T7', 'Olası', 'Avalonian ödülü'), drop('Avalonian Bag', 'T7_BAG', 'T7', 'Nadir', 'Avalonian ödülü')]),
    mob('corrupted-demon-family', 'Corrupted Demon', 'Demon', 'mob', 'Corrupted Dungeon', 'high', '👁️', '#fb7185', '28K', '380–620', '18K', 'Run bazlı', 'Corrupted içindeki arena baskısını temsil eden; rakip oyuncu istilasıyla birlikte risklenen aile.', ['Arena duvarı', 'Fear pulse'], ['Fear pulse sırasında kenara çekil', 'Rakip oyuncu sesini ayrı takip et'], 'Solo PvP', [drop('Corrupted Chest', 'T6_ARTEFACT_ARMOR_LEATHER_UNDEAD', 'T6', 'Olası', 'Corrupted reward'), drop('Rune', 'T6_RUNE', 'T6', 'Sık', 'Genel ödül')]),
    mob('hellgate-demon-family', 'Hellgate Demon', 'Demon', 'boss', 'Hellgate', 'high', '😈', '#ef4444', '54K', '640–980', '27K', 'Instance', 'Hellgate final encounter; iki takımın PvP baskısı ve boss alanı aynı anda yönetilir.', ['Demon cone', 'Fear wave'], ['Fear wave öncesi mesafe aç', 'Rakip takımın cooldown penceresini izle'], 'Group PvP', [drop('Demonic Chest', 'T7_2H_AXE', 'T7', 'Nadir', 'Hellgate reward'), drop('Soul', 'T7_SOUL', 'T7', 'Olası', 'Demon loot')], 'hellgate'),
    mob('mists-lich', 'Mist Lich', 'Undead', 'boss', 'Mists', 'high', '🧙', '#8b5cf6', '42K', '520–880', '21K', '15–30 dk', 'Mists bölgesinin zorlu boss varyantı; teleport, alan laneti ve sandık koruması ile bilinir.', ['Teleport chain', 'Curse field'], ['Teleport işaretini takip et', 'Curse alanını güvenli kenara taşı'], 'Duo / Small group', [drop('Mists Chest', 'T7_MAIN_FROSTSTAFF', 'T7', 'Olası', 'Mists boss'), drop('Soul', 'T7_SOUL', 'T7', 'Nadir', 'Undead loot')], 'lich'),
    mob('static-keeper-elder-ops', 'Keeper Elder', 'Keeper', 'boss', 'Static Dungeon', 'high', '🗿', '#f59e0b', '64K', '720–1100', '31K', '20–40 dk', 'Static dungeon final encounter; tank yönü ve healer dispel zamanlaması savaşın anahtarıdır.', ['Boulder line', 'Ground slam'], ['Boulder çizgisini kesme', 'Ground slam sonrası DPS penceresini kullan'], 'Tank / Healer / DPS', [drop('Keeper Artefact', 'T8_ARTEFACT_ARMOR_CLOTH_KEEPER', 'T8', 'Nadir', 'Keeper boss'), drop('T8 Bag', 'T8_BAG', 'T8', 'Olası', 'Dungeon chest')], 'keeper'),
    mob('avalonian-earthmother-ops', 'Avalonian Earthmother', 'Avalonian', 'boss', 'Roads of Avalon', 'high', '🌿', '#22c55e', '78K', '950–1420', '48K', '30–60 dk', 'Kök alanları ve faz değişimleriyle yedi kişilik ekip koordinasyonu ister.', ['Root prison', 'Nature burst'], ['Root prison hedefini hızlı kurtar', 'Burst fazında çiçek çekirdeklerini önceliklendir'], 'Full group', [drop('Avalonian Bag', 'T8_BAG', 'T8', 'Olası', 'Avalonian boss'), drop('Leather Artefact', 'T8_ARTEFACT_ARMOR_PLATE_HELL', 'T8', 'Çok nadir', 'Artefact')], 'earthmother'),
    mob('world-behemoth-ops', 'World Behemoth', 'World Boss', 'event', 'Black Zone / Open World', 'high', '🐲', '#ef4444', '180K', '1100–1850', '110K', 'Etkinlik penceresi', 'Açık dünya etkinlik bossu; kalabalıkta hedef önceliği ve loot taşıma riski birlikte yönetilir.', ['Raid roar', 'Adds wave'], ['Adds dalgasını kes', 'Loot zamanı için güvenli çıkışı önceden işaretle'], 'Large group', [drop('T8 Bag', 'T8_BAG', 'T8', 'Olası', 'World boss'), drop('Fame Book', 'T8_SKILLBOOK', 'T8', 'Nadir', 'World boss'), drop('Weapon Artefact', 'T8_ARTEFACT_MAIN_SPEAR_KEEPER', 'T8', 'Çok nadir', 'Rare artefact')], 'behemoth'),
    mob('faction-general-ops', 'Faction General', 'Faction', 'event', 'Faction Warfare', 'medium', '🚩', '#22c55e', '92K', '760–1200', '55K', 'Etkinlik penceresi', 'Faction operasyonlarının hedefi; oyuncu yoğunluğu ve savaş bölgesi riski drop değerinden bağımsızdır.', ['Banner buff', 'Reinforcement'], ['Banner taşıyıcısını koru', 'Reinforcement yönünü scoutla'], 'Faction group', [drop('Faction Chest', 'T6_OFF_SHIELD', 'T6', 'Olası', 'Faction reward'), drop('Fame Book', 'T6_SKILLBOOK', 'T6', 'Sık', 'Faction loot')]),
    mob('world-tree-event-ops', 'World Tree Event', 'Resource Guardian', 'event', 'Open World / Black Zone', 'medium', '🌳', '#84cc16', '—', '—', 'Toplama bazlı', 'Toplama penceresi', 'Mob değil; kaynak etkinliği olarak işlenir. Toplayıcı, taşıma ve PvP riskini tek kayıtta izler.', ['Kaynak yenilenmesi', 'Gank riski'], ['Doluluk oranını takip et', 'Çıkış rotasını taşıma öncesi belirle'], 'Gatherer group', [drop('Fiber', 'T6_FIBER', 'T6', 'Sık', 'Biyom kaynağı'), drop('Fiber', 'T7_FIBER', 'T7', 'Olası', 'Biyom kaynağı'), drop('Fiber', 'T8_FIBER', 'T8', 'Nadir', 'Biyom kaynağı')]),
    mob('mists-rare-beast', 'Mist Beast', 'Beast', 'mob', 'Mists', 'medium', '🐺', '#c084fc', '12K', '260–390', '5.4K', '8–15 dk', 'Mists içindeki hızlı avcı ailesi; kısa menzilli burst ve ani yön değişimi kullanır.', ['Hızlı sıçrama', 'Yara'], ['Sıçrama işaretinden çık', 'Yara yığınını temizlemeden greed yapma'], 'Solo / Duo', [drop('Mists Chest', 'T6_MAIN_FROSTSTAFF', 'T6', 'Olası', 'Mists ödülü'), drop('Hide', 'T6_HIDE', 'T6', 'Sık', 'Bölgesel drop')]),
    mob('open-world-giant', 'Open World Giant', 'Giant', 'mob', 'Black Zone / Open World', 'high', '🦣', '#ef4444', '36K', '520–780', '16K', '10–20 dk', 'Açık dünyada büyük rota kesen ağır yaratık; alan vuruşu ve korku baskısı yaratır.', ['Yer sarsıntısı', 'Korku'], ['Yer sarsıntısında menzili aç', 'Korku dalgasında tank yönünü koru'], 'Duo / Group', [drop('Giant Heart', 'T7_OFF_TOTEM_KEEPER', 'T7', 'Nadir', 'Open world özel düşümü'), drop('Rune', 'T7_RUNE', 'T7', 'Olası', 'Genel ödül')]),
    mob('keeper-elder-guardian', 'Keeper Guardian', 'Keeper', 'mob', 'Static Dungeon', 'high', '🛡️', '#f59e0b', '16K', '360–540', '7.2K', '8–16 dk', 'Keeper ailesinin kalkanlı elit varyantı; ön cepheyi sabitleyerek healerı baskılar.', ['Kalkan duvarı', 'Ağır darbe'], ['Kalkan aktifken arkaya geç', 'Ağır darbe öncesi dağılımı aç'], 'Group', [drop('Keeper Rune', 'T7_RUNE', 'T7', 'Olası', 'Keeper loot'), drop('Plate Artefact', 'T7_ARTEFACT_ARMOR_PLATE_HELL', 'T7', 'Nadir', 'Artefact')]),
    mob('morgana-demon-ops', 'Morgana Demon', 'Morgana', 'boss', 'Static Dungeon / Open World', 'high', '👿', '#a855f7', '48K', '600–980', '24K', 'Instance', 'Morgana demon bossu; kanal, fear ve ateş alanlarını birlikte yönetmeyi gerektirir.', ['Fear channel', 'Fire ring'], ['Kanalı interrupt et', 'Fire ringi dış halkaya taşı'], 'Tank / Healer / DPS', [drop('Morgana Artefact', 'T7_ARTEFACT_ARMOR_PLATE_MORGANA', 'T7', 'Nadir', 'Morgana boss'), drop('Morgana Chest', 'T7_ARTEFACT_ARMOR_PLATE_MORGANA', 'T7', 'Olası', 'Dungeon reward')]),
    mob('avalonian-construct-ops', 'Avalonian Construct', 'Avalonian', 'boss', 'Roads of Avalon', 'high', '🤖', '#38bdf8', '70K', '860–1300', '42K', '25–50 dk', 'Avalonian mekanik bossu; enerji alanı, ön koni ve çekirdek fazı grup koordinasyonu ister.', ['Enerji alanı', 'Çekirdek fazı'], ['Enerji alanında güvenli noktayı koru', 'Çekirdek açıldığında burst sırala'], 'Full group', [drop('Avalonian Shard', 'T8_SHARD_AVALONIAN', 'T8', 'Olası', 'Avalonian reward'), drop('Plate Artefact', 'T8_ARTEFACT_ARMOR_PLATE_HELL', 'T8', 'Nadir', 'Artefact')]),
    mob('hellgate-guardian-ops', 'Hellgate Guardian', 'Demon', 'boss', 'Hellgate', 'high', '🔥', '#ef4444', '38K', '480–760', '19K', 'Instance', 'Hellgate guardianı; boss mekaniği ile rakip takım baskısı aynı anda okunur.', ['Cone blast', 'Rift pulse'], ['Bossu merkezden uzaklaştırma', 'Rift pulse sırasında rakip açılarını izle'], 'Group PvP', [drop('Hellgate Chest', 'T6_2H_CROSSBOW', 'T6', 'Olası', 'Hellgate reward'), drop('Demonic Shard', 'T6_OFF_DEMONIC', 'T6', 'Nadir', 'Hellgate loot')]),
    mob('faction-war-chief', 'Faction War Chief', 'Faction', 'boss', 'Faction Warfare', 'high', '🚩', '#22c55e', '110K', '900–1500', '62K', 'Etkinlik penceresi', 'Faction savaşının ağır hedefi; banner güçlendirmesi ve reinforcement dalgaları yönetilir.', ['Banner aura', 'Reinforcement'], ['Bannerı güvenli tut', 'Takviye yönünü önceden işaretle'], 'Faction group', [drop('Faction Chest', 'T7_OFF_SHIELD', 'T7', 'Olası', 'Faction reward'), drop('Faction Token', 'T7_ARTEFACT_ARMOR_PLATE_MORGANA', 'T7', 'Sık', 'Faction loot')]),
    mob('corrupted-stalker', 'Corrupted Stalker', 'Demon', 'boss', 'Corrupted Dungeon', 'high', '👁️', '#fb7185', '33K', '430–700', '20K', 'Run bazlı', 'Corrupted boss varyantı; arena kontrolü, purge ve rakip oyuncu baskısı birlikte düşünülür.', ['Purge field', 'Dash'], ['Purge alanını böl', 'Dash sonrası karşı burst sakla'], 'Solo PvP', [drop('Corrupted Chest', 'T7_ARTEFACT_ARMOR_LEATHER_UNDEAD', 'T7', 'Olası', 'Corrupted reward'), drop('Demon Artefact', 'T7_2H_AXE', 'T7', 'Nadir', 'Rare drop')]),
    mob('roads-ancient-guardian', 'Roads Ancient Guardian', 'Avalonian', 'mob', 'Roads of Avalon', 'medium', '🗿', '#0ea5e9', '14K', '300–460', '6.5K', '8–18 dk', 'Roads kaynak odalarını koruyan eski guardian ailesi; kısa süreli stun ve shockwave üretir.', ['Stun pulse', 'Shockwave'], ['Stun öncesi cleanse hazırla', 'Shockwave çizgisini boşalt'], 'Duo / Group', [drop('Avalonian Shard', 'T6_SHARD_AVALONIAN', 'T6', 'Olası', 'Roads loot'), drop('Rune', 'T6_RUNE', 'T6', 'Sık', 'Genel ödül')]),
  ];
  const phases = {
    griffin: [{ name: 'İz sürme', task: 'Dalış işaretini takip et, grubun görüş hattını koru.', duration: 20 }, { name: 'Dalış', task: 'Dalış alanından çık; inişten sonra burst kullan.', duration: 15 }, { name: 'Loot penceresi', task: 'Tüy veya sandık düştüyse taşıyıcı ve çıkış rotasını kontrol et.', duration: 25 }],
    hellgate: [{ name: 'Arena açılışı', task: 'Tank bossu merkeze alırken rakip takım girişini scoutla.', duration: 30 }, { name: 'Fear wave', task: 'Fear çizgisini kır, healer dispel ve purge sırasını uygula.', duration: 20 }, { name: 'Bitiriş', task: 'Boss ve rakip cooldownlarını birlikte okuyup güvenli loot al.', duration: 25 }],
    lich: [{ name: 'Teleport zinciri', task: 'İşaretli teleport noktalarını önceden boşalt.', duration: 25 }, { name: 'Curse field', task: 'Lanet alanını dış halkaya taşı ve melee alanını açık tut.', duration: 30 }, { name: 'Sandık', task: 'Sandık açmadan önce Mists çıkışını kontrol et.', duration: 20 }],
    keeper: [{ name: 'Ön cephe', task: 'Tank yönünü sabitler, DPS ön koniden uzak kalır.', duration: 30 }, { name: 'Boulder', task: 'Çizgisel kayayı kesme; healer güvenli koridorda kalsın.', duration: 25 }, { name: 'Slam sonrası', task: 'Ground slam bitince kısa burst penceresini değerlendir.', duration: 20 }],
    earthmother: [{ name: 'Kök alanı', task: 'Root prison hedefini cleanse et ve çiçek çekirdeğini işaretle.', duration: 35 }, { name: 'Doğa burstü', task: 'Çekirdekleri önceliklendir, tank bossu güvenli halkaya taşısın.', duration: 35 }, { name: 'Çıkış', task: 'Boss ölmeden önce loot taşıyıcısı ve portal görevini belirle.', duration: 30 }],
    behemoth: [{ name: 'Toplanma', task: 'Raid lideri hedef önceliğini ve kaçış yönünü duyurur.', duration: 40 }, { name: 'Adds', task: 'Adds dalgasını kontrol et; healer ve taşıyıcıyı koru.', duration: 35 }, { name: 'Loot', task: 'Değerli loot için dönüş rotasını ve scout bilgisini doğrula.', duration: 30 }]
  };
  const spawnEvents = [
    { name: 'World Boss penceresi', zone: 'Black Zone', utc: 18, duration: 45, risk: 'Yüksek', note: 'Kalabalık raid ve taşıma riski.' },
    { name: 'Faction General', zone: 'Faction Warfare', utc: 16, duration: 30, risk: 'Orta', note: 'Faction savaşı yoğunluğu.' },
    { name: 'Mists rare chest cycle', zone: 'Mists', utc: 12, duration: 20, risk: 'Orta-Yüksek', note: 'Solo/duo için hızlı rota.' },
    { name: 'Avalonian portal window', zone: 'Roads of Avalon', utc: 21, duration: 60, risk: 'Yüksek', note: 'Portal ve çıkış scout gerektirir.' }
  ];
  const dungeons = [
    { name: 'Static Keeper', tier: 7, city: 'Martlock', time: 45, risk: 'Yüksek', exit: 'Yakın portal / güvenli geçiş', roles: '1 Tank · 1 Healer · 3 DPS', loot: 480000 },
    { name: 'Mists Griffin Hunt', tier: 6, city: 'Brecilien', time: 35, risk: 'Orta-Yüksek', exit: 'En yakın Mist çıkışı', roles: 'Mobil solo / duo', loot: 220000 },
    { name: 'Avalonian Roads', tier: 8, city: 'Brecilien', time: 60, risk: 'Yüksek', exit: 'Scout edilmiş portal', roles: 'Tank · Healer · DPS · Support', loot: 820000 },
    { name: 'Corrupted Dungeon', tier: 6, city: 'Caerleon', time: 35, risk: 'Orta', exit: 'Kişisel instance çıkışı', roles: 'Solo PvP', loot: 260000 }
  ];
  const gathering = [
    { resource: 'Fiber', biome: 'Swamp', zone: 'Thetford çevresi', tier: 6, price: 740, yield: 420, danger: 'Düşük-Orta' },
    { resource: 'Hide', biome: 'Steppe', zone: 'Bridgewatch çevresi', tier: 6, price: 820, yield: 360, danger: 'Orta' },
    { resource: 'Ore', biome: 'Mountain', zone: 'Fort Sterling çevresi', tier: 7, price: 1180, yield: 280, danger: 'Orta-Yüksek' },
    { resource: 'Wood', biome: 'Forest', zone: 'Lymhurst çevresi', tier: 6, price: 690, yield: 460, danger: 'Düşük-Orta' },
    { resource: 'Stone', biome: 'Highland', zone: 'Martlock çevresi', tier: 7, price: 990, yield: 300, danger: 'Orta' }
  ];
  const encyclopedia = [
    { type: 'İçerik', title: 'Mists', body: 'Solo ve duo keşif alanı; chest, rare mob ve oyuncu istilası riskini aynı anda taşır.' },
    { type: 'Sistem', title: 'Focus', body: 'Craft veya refine kararını şehir bonusu, uzmanlık ve güncel fiyatla birlikte değerlendir.' },
    { type: 'Bölge', title: 'Roads of Avalon', body: 'Portal bağlantısı değişken; çıkış, taşıma kapasitesi ve scout bilgisi kâr kadar önemlidir.' },
    { type: 'İçerik', title: 'Corrupted Dungeon', body: 'Solo PvP ve PvE gelirini bir arada test eden instance; build ve karşı build kritik.' },
    { type: 'Sistem', title: 'Market vergisi', body: 'Net kâr hesaplarında satış vergisi, alış emri ve listeleme maliyetini ayrı düşün.' },
    { type: 'Bölge', title: 'Black Zone', body: 'Yüksek kaynak ve fame potansiyeli; ölüm maliyeti ve güvenli dönüş rotası her planda yer almalı.' }
  ];
  window.AlbionOperationsData = { encounters, phases, spawnEvents, dungeons, gathering, encyclopedia };
})();
