/* Boss rehearsal surface: visual phase timeline, attack markers and a lightweight countdown. */
(function () {
  const t = (key, fallback) => window.t?.(key, fallback) || fallback; const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char])); let root; let selected; let phase = 0; let timer; let remaining = 0;
  function phases() { const entry = window.AlbionOperationsData?.encounters?.find((item) => item.id === selected); return entry ? window.AlbionOperationsData.phases[entry.phaseKey] || [] : []; }
  function render() { const entry = window.AlbionOperationsData?.encounters?.find((item) => item.id === selected); const list = phases(); if (!entry || !list.length) return; const current = list[phase] || list[0]; root.querySelector('#opsCombatBody').innerHTML = `<div class="ops-combat-card"><div class="ops-combat-top"><div><span class="operations-view-kicker"><i class="fa-solid fa-shield-halved"></i>${esc(entry.family)}</span><h2>${esc(entry.name)}</h2><p>${esc(entry.summary)}</p></div><span class="ops-threat ops-risk-${esc(entry.risk)}">${esc(entry.risk)}</span></div><div class="ops-attack-timeline">${list.map((item, index) => `<button type="button" class="ops-timeline-node ${index === phase ? 'is-active' : index < phase ? 'is-done' : ''}" data-ops-phase="${index}"><i class="fa-solid ${index === 0 ? 'fa-eye' : index === list.length - 1 ? 'fa-box-open' : 'fa-bolt'}"></i><b>${index + 1}</b><span>${esc(item.name)}</span><small>${item.duration}s</small></button>`).join('')}</div><div class="ops-phase-card"><span>${esc(t('operations-phase', 'Faz'))} ${phase + 1} · ${esc(current.name)}</span><strong>${esc(current.task)}</strong><div class="ops-progress"><i style="width:${Math.round((phase + 1) / list.length * 100)}%"></i></div><small>${remaining > 0 ? `${remaining}s prova sayacı` : `${current.duration} sn önerilen hazırlık`}</small></div><div class="ops-combat-actions"><button type="button" class="ops-primary-action" data-ops-run><i class="fa-solid fa-play"></i>${esc(t('operations-run', 'Simülasyonu başlat'))}</button><button type="button" class="ops-small-action" data-ops-reset>${esc(t('operations-reset', 'Sıfırla'))}</button><button type="button" class="ops-small-action" data-ops-next>${esc(t('operations-next', 'Sonraki adım'))}</button></div></div>`; }
  function run() { clearInterval(timer); remaining = phases()[phase]?.duration || 0; render(); timer = setInterval(() => { remaining -= 1; if (remaining <= 0) { clearInterval(timer); remaining = 0; phase = Math.min(phase + 1, phases().length - 1); } render(); }, 1000); }
  function mount() { root = document.getElementById('operations-combat-root'); if (!root || root.dataset.ready) return; root.dataset.ready = 'true'; const bosses = (window.AlbionOperationsData?.encounters || []).filter((item) => item.phaseKey); root.innerHTML = `<label class="ops-field"><span>Boss seç</span><select id="opsCombatSelect">${bosses.map((item) => `<option value="${esc(item.id)}">${esc(item.name)}</option>`).join('')}</select></label><div id="opsCombatBody"></div>`; selected = bosses[0]?.id; root.querySelector('#opsCombatSelect').addEventListener('change', (event) => { selected = event.target.value; phase = 0; remaining = 0; clearInterval(timer); render(); }); root.addEventListener('click', (event) => { const step = event.target.closest('[data-ops-phase]'); if (step) { phase = Number(step.dataset.opsPhase); remaining = 0; clearInterval(timer); render(); } if (event.target.closest('[data-ops-next]')) { phase = Math.min(phase + 1, phases().length - 1); remaining = 0; render(); } if (event.target.closest('[data-ops-reset]')) { phase = 0; remaining = 0; clearInterval(timer); render(); } if (event.target.closest('[data-ops-run]')) run(); }); render(); }
  document.addEventListener('DOMContentLoaded', mount);
})();
