/* PvP analysis: live handoff, opponent history, build comparison and local notes. */
(function () {
  const t = (key, fallback) => window.t?.(key, fallback) || fallback; const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char])); const KEY = 'aot_pnasf_ops_pvp_history'; let history = [];
  async function load() { try { const raw = await window.miniappsAI?.storage?.getItem(KEY, { area: 'persistent' }); return raw ? JSON.parse(raw) : []; } catch (error) { return []; } }
  async function save() { try { await window.miniappsAI?.storage?.setItem(KEY, JSON.stringify(history.slice(0, 80)), { area: 'persistent' }); } catch (error) {} }
  function historyList(root) { root.querySelector('#opsPvpHistory').innerHTML = history.length ? history.map((item, index) => `<article><div><strong>${esc(item.name)}</strong><span>${esc(item.build || 'Build bilinmiyor')}</span></div><b>${item.kills}K / ${item.deaths}D</b><small>${esc(item.note || 'Not yok')} · ${new Date(item.at).toLocaleDateString('tr-TR')}</small><button class="ops-small-action" data-remove-pvp="${index}" aria-label="Sil"><i class="fa-solid fa-xmark"></i></button></article>`).join('') : '<div class="ops-empty">Henüz rakip kaydı yok.</div>'; }
  function compare(root) { const one = root.querySelector('#opsCompareOne').value.trim(); const two = root.querySelector('#opsCompareTwo').value.trim(); const a = history.find((item) => item.name.toLocaleLowerCase() === one.toLocaleLowerCase()); const b = history.find((item) => item.name.toLocaleLowerCase() === two.toLocaleLowerCase()); root.querySelector('#opsPvpCompareResult').innerHTML = `<table class="ops-compare-table"><thead><tr><th>Ölçüm</th><th>${esc(one || 'Rakip A')}</th><th>${esc(two || 'Rakip B')}</th></tr></thead><tbody><tr><td>Build</td><td>${esc(a?.build || 'Kayıt yok')}</td><td>${esc(b?.build || 'Kayıt yok')}</td></tr><tr><td>Kill / death</td><td>${a ? `${a.kills} / ${a.deaths}` : '—'}</td><td>${b ? `${b.kills} / ${b.deaths}` : '—'}</td></tr><tr><td>Karşı oyun notu</td><td>${esc(a?.note || '—')}</td><td>${esc(b?.note || '—')}</td></tr></tbody></table>`; }
  async function mount() { const root = document.getElementById('operations-pvp-root'); if (!root || root.dataset.ready) return; root.dataset.ready = 'true'; history = await load(); root.innerHTML = `<div class="ops-pvp-card"><div class="ops-form-card"><label class="ops-field"><span>${t('operations-pvpName', 'Oyuncu adı')}</span><input id="opsPvpName" type="text" placeholder="Oyuncu veya guild"></label><button type="button" class="ops-primary-action" data-ops-pvp-search><i class="fa-solid fa-crosshairs"></i>${t('operations-pvpSearch', "Killboard'da ara")}</button><div id="opsPvpStatus" class="ops-inline-status"></div></div><form class="ops-form-card" data-pvp-record><label class="ops-field"><span>Rakip geçmişi kaydı</span><input name="name" required placeholder="Oyuncu adı"><input name="build" placeholder="Build / silah"><div class="ops-compare-grid"><input name="kills" type="number" min="0" value="0" placeholder="Kill"><input name="deaths" type="number" min="0" value="0" placeholder="Death"></div><textarea name="note" rows="3" placeholder="Bölge, cooldown, kaçış alışkanlığı…"></textarea></label><button class="ops-primary-action" type="submit">${t('operations-saveNote', 'Notu kaydet')}</button></form></div><div class="ops-form-card"><div class="ops-section-head"><h3>Rakip build karşılaştırması</h3><span>kayıtlı oyuncular</span></div><div class="ops-compare-grid"><input id="opsCompareOne" placeholder="Rakip A"><input id="opsCompareTwo" placeholder="Rakip B"><button class="ops-primary-action" type="button" data-compare-pvp>Karşılaştır</button></div><div id="opsPvpCompareResult"></div></div><div id="opsPvpHistory" class="ops-history-list"></div>`; root.querySelector('[data-ops-pvp-search]').addEventListener('click', () => { const name = root.querySelector('#opsPvpName').value.trim(); if (!name) return; root.querySelector('#opsPvpStatus').textContent = `${name} için PvP bölümündeki canlı killboard aramasına yönlendiriliyorsun.`; document.querySelector('[data-tab="tab-pvp"]')?.click(); const input = document.querySelector('#playerName'); if (input) { input.value = name; document.querySelector('#pvpSearchForm')?.requestSubmit(); } }); root.addEventListener('submit', async (event) => { if (!event.target.matches('[data-pvp-record]')) return; event.preventDefault(); const form = new FormData(event.target); history.unshift({ name: form.get('name'), build: form.get('build'), kills: Number(form.get('kills')) || 0, deaths: Number(form.get('deaths')) || 0, note: form.get('note'), at: Date.now() }); await save(); historyList(root); event.target.reset(); }); root.addEventListener('click', async (event) => { const remove = event.target.closest('[data-remove-pvp]'); if (remove) { history.splice(Number(remove.dataset.removePvp), 1); await save(); historyList(root); } if (event.target.closest('[data-compare-pvp]')) compare(root); }); historyList(root); }
  document.addEventListener('DOMContentLoaded', mount);
})();
