/* Live event and spawn board: UTC schedule, countdowns and persistent watch flags. */
(function () {
  const t = (key, fallback) => window.t?.(key, fallback) || fallback;
  const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
  const KEY = 'aot_pnasf_ops_spawn_watch'; let root; let watched = {}; let timer;
  const nextDate = (utc) => { const now = new Date(); const next = new Date(now); next.setUTCHours(utc, 0, 0, 0); if (next <= now) next.setUTCDate(next.getUTCDate() + 1); return next; };
  const countdown = (date) => { const ms = Math.max(0, date - new Date()); const hours = Math.floor(ms / 3600000); const minutes = Math.floor(ms % 3600000 / 60000); const seconds = Math.floor(ms % 60000 / 1000); return `${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`; };
  async function save() { try { await window.miniappsAI?.storage?.setItem(KEY, JSON.stringify(watched), { area: 'persistent' }); } catch (error) {} }
  function render() { const events = window.AlbionOperationsData?.spawnEvents || []; root.querySelector('#opsSpawnList').innerHTML = events.map((event, index) => { const date = nextDate(event.utc); return `<article class="ops-spawn-card ${index === 0 ? 'is-next' : ''}"><div class="ops-spawn-icon"><i class="fa-solid fa-tower-broadcast"></i></div><div class="ops-spawn-copy"><div class="ops-spawn-title"><h3>${esc(event.name)}</h3><span class="ops-risk-${event.risk.includes('Yüksek') ? 'high' : 'medium'}">${esc(event.risk)}</span></div><p>${esc(event.zone)} · ${esc(event.note)}</p><small>UTC ${String(event.utc).padStart(2, '0')}:00 · ${event.duration} dk pencere</small></div><div class="ops-spawn-time"><strong data-ops-countdown="${index}">${countdown(date)}</strong><button type="button" class="ops-small-action ${watched[index] ? 'is-watched' : ''}" data-ops-watch="${index}" aria-label="${esc(event.name)} takip">${watched[index] ? 'Takipte' : 'Takip et'}</button></div></article>`; }).join(''); }
  function tick() { if (document.hidden || root?.closest('#tab-operations')?.classList.contains('hidden')) return; root?.querySelectorAll('[data-ops-countdown]').forEach((node) => { const event = window.AlbionOperationsData.spawnEvents[Number(node.dataset.opsCountdown)]; if (event) node.textContent = countdown(nextDate(event.utc)); }); }
  async function mount() { root = document.getElementById('operations-spawn-root'); if (!root || root.dataset.ready) return; root.dataset.ready = 'true'; try { const raw = await window.miniappsAI?.storage?.getItem(KEY, { area: 'persistent' }); watched = raw ? JSON.parse(raw) : {}; } catch (error) { watched = {}; } root.innerHTML = `<div class="ops-spawn-toolbar"><span class="operations-view-kicker"><i class="fa-solid fa-clock"></i>${t('operations-spawn', 'Spawn & Etkinlik Takibi')}</span><small>Sunucu saatinden bağımsız UTC takvimi · her gün yenilenir</small></div><div id="opsSpawnList" class="ops-spawn-list"></div>`; root.addEventListener('click', async (event) => { const button = event.target.closest('[data-ops-watch]'); if (!button) return; const id = button.dataset.opsWatch; watched[id] = !watched[id]; await save(); render(); }); render(); timer = setInterval(tick, 1000); }
  document.addEventListener('DOMContentLoaded', mount);
})();
